<img style="float: left;" src="attachment:D2Klogo.png" width="20%"> 

<center>

# Welcome to COMP 680 #
### Statistics for Computing and Data Science ###

### Homework 1 ###

Here's your real homework starts:P. Please write your code with appropriate comments and informative names. Feel free to insert more cells as you see necessary. 

**Question 1**:
Create four Python variables with different data types.

In [18]:
# (1) 
x_1 = 45
x_2 = 45.6
x_3 = True
x_4 = "hello"

print(type(x_1))
print(type(x_2))
print(type(x_3))
print(type(x_4))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


***
**Question 2**:
Create a Python list containing 5 numeric values.

In [23]:
my_list_num = [1, 2, 3, 4, 5]
print(type(my_list_num))
print(my_list_num)

<class 'list'>
[1, 2, 3, 4, 5]


***
**Question 3**:
Perform an arithmetic operation on a subset of elements in the list you just created.

In [26]:
# your code here
my_list_num[:3] = [6, 7, 8]
my_list_num[3] = my_list_num[3] + 1
my_list_num[4] = my_list_num[4] + 1
print(my_list_num)

[6, 7, 8, 8, 9]


***
**Question 4**:
Create a Python list containing 3 string values.

In [27]:
my_list_str = ["hello", " ", "world"]
print(my_list_str)
print(type(my_list_str))

['hello', ' ', 'world']
<class 'list'>


***
**Question 5**:
Append 2 more strings to the end of this Python list you just created.

In [28]:
# appending to the originarl list
my_list_str.append(" ")
my_list_str.append("!")
print(my_list_str)

['hello', ' ', 'world', ' ', '!']


***
**Question 6**:
Combine your two Python lists into a single list.

In [29]:
my_list = my_list_num.copy()
my_list.extend(my_list_str)
print(my_list)

[6, 7, 8, 8, 9, 'hello', ' ', 'world', ' ', '!']


***
**Question 7**:
Use any five Python functions to do some manipulations on your variables or lists. Check [here](https://docs.python.org/3/library/functions.html) for some build-in functions in [the Python Standard Library](https://docs.python.org/3/library/index.html). 

In [30]:
# get the indexes of all the spaces
space_index = [i for i, x in enumerate(my_list) if x == " "]

# replace the spaces with dashes
for i in space_index:
    my_list[i] = "-"

# print the list
print(my_list)

# identify the strings, get the index of the strings
str_index = [i for i, x in enumerate(my_list) if type(x) == str]

# uppercase all the strings
for i in str_index:
    my_list[i] = my_list[i].upper()

# convert all the elements to string
my_list = [str(i) for i in my_list]

# sort the list
my_list.sort(reverse=True)

# print the list
print(my_list)

# slice using the slice() function
my_list = my_list[slice(0, 7)]

# print the list
print(my_list)

# list of the functions used in this cell, not methods
# enumerate()
# print()
# type()
# str()
# slice()



[6, 7, 8, 8, 9, 'hello', '-', 'world', '-', '!']
['WORLD', 'HELLO', '9', '8', '8', '7', '6', '-', '-', '!']
['WORLD', 'HELLO', '9', '8', '8', '7', '6']


***
**Question 8**:
Use any five Python methods to do some manipulations on your variables or lists. Check [here](https://docs.python.org/3/tutorial/datastructures.html) for some methods you can apply to Python lists or [Numpy array methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

In [31]:
import numpy as np

# append each element to the list into a new list, if the element is a string, slice it to have all the characters in the string
new_list = []
for i in my_list:
    if type(i) == str:
        for j in i:
            new_list.append(j)
    else:
        new_list.append(i)

# print the new list
print(new_list)

# reverse the list
new_list.reverse()

# print the list
print(new_list)

# create an empty array to store the numbers, the size of the previous list is the size of the array
new_list_num = np.zeros(len(new_list))
# obtain the corresponding ascci code for each character in the list and store it in the array
for i in range(len(new_list)):
    new_list_num[i] = ord(new_list[i])

# print the array
print(new_list_num)

# change the type of the array to integer
new_list_num = new_list_num.astype(int)

# print the array
print(new_list_num)

# sort the array
new_list_num.sort()

# print the array
print(new_list_num)

# obtain the corresponding character for each number in the array and store it in a new list
new_list = []
for i in new_list_num:
    new_list.append(chr(i))

# extend the list with the new list
my_list.extend(new_list)

# print the list
print(my_list)

# methods used in this cell
# append()
# zeros()
# astype()
# sort()
# extend()



['W', 'O', 'R', 'L', 'D', 'H', 'E', 'L', 'L', 'O', '9', '8', '8', '7', '6']
['6', '7', '8', '8', '9', 'O', 'L', 'L', 'E', 'H', 'D', 'L', 'R', 'O', 'W']
[54. 55. 56. 56. 57. 79. 76. 76. 69. 72. 68. 76. 82. 79. 87.]
[54 55 56 56 57 79 76 76 69 72 68 76 82 79 87]
[54 55 56 56 57 68 69 72 76 76 76 79 79 82 87]
['WORLD', 'HELLO', '9', '8', '8', '7', '6', '6', '7', '8', '8', '9', 'D', 'E', 'H', 'L', 'L', 'L', 'O', 'O', 'R', 'W']


***
**Question 9**:
Create a two-dimensional NumPy array.

In [32]:
my_2d_array = np.eye(3, 3)
print(my_2d_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***
**Question 10**:
Print a subset of the rows and columns of the two-dimensional Numpy array you just created.

In [33]:
# Print a subset of the rows
print(my_2d_array[1:, :])

# Print a subset of the columns
print(my_2d_array[:, 1:])

[[0. 1. 0.]
 [0. 0. 1.]]
[[0. 0.]
 [1. 0.]
 [0. 1.]]


***
**Question 11**: Suppose that a fair coin is tossed repeatedly until both a head and tail have appeared at least once. 

1. Describe the sample space $\Omega$. Is it finite, countable infinite, or uncountable infinite?
1. Define a random variable $X$ to be the number of total tosses needed. Is $X$ a discrete or continuous random variable?
1. Derive the Probability Mass Function for $X$.

**Solution**:

1) The sample space can be constructed as follows:
$
\Omega = \{HT, HHT, HHHT, HHHHT, \ldots, TH, TTH, TTTH, TTTTH, \ldots\}
$

Here, we have two sequences: one starting with H and followed by a series of Hs until a T appears, and another starting with T and followed by a series of Ts until an H appears.

The sample space is countably infinite because we can have an infinite number of tosses before getting both a head and a tail, but we can count all possible outcomes in a sequence (as shown above).

2) $X$ is a discrete random variable because it can take on a finite or countably infinite number of distinct values (in this case, the number of tosses, which are whole numbers).

3) To find the Probability Mass Function (PMF) of $X$, we need to find the probability that $X$ takes on each of its possible values. Let's denote $P(X=k)$ as the probability that exactly \(k\) tosses are needed.

The PMF can be derived as follows:

$
P(X=2) = P(\text{HT or TH}) = \frac{1}{2} \cdot \frac{1}{2} + \frac{1}{2} \cdot \frac{1}{2} = \frac{1}{2}
$

$
P(X=k) = \left( \frac{1}{2} \right)^{k} + \left( \frac{1}{2} \right)^{k} = \left( \frac{1}{2} \right)^{k-1}, \quad k > 2
$

So, the PMF of $X$ is given by:

$
P(X=k) = 
\begin{cases} 
  0 & \text{if } k < 2 \\
  \left( \frac{1}{2} \right)^{k-1} & \text{if } k \geq 2 
\end{cases}
$

***
**Question 12**: Consider rolling a die once. Let $A = \{1, 2\}$, $B = \{2, 4, 6\}$, and $C = \{1, 4\}$. Show that $A$ and $B$ are independent, but not independent conditioned on $C$.

**Note**: Event $A = \{1, 2\}$ means the outcome is 1 or 2.

**Solution**:

Considering we have a fair dice:

To prove that $A \perp B$ this has to be true $P(A|B) = P(A)$ and $P(B|A) = P(B)$

$P(A|B) = \frac{P(A\cap B}{P(B)} = \frac{P(X=2)}{P(X=\{2,4,6\})} = \frac{1/ 6}{1/ 2} = \frac{1}{3} = P(A)$ 

$P(B|A) = \frac{P(A\cap B}{P(A)} = \frac{P(X=2)}{P(X=\{1,2\})} = \frac{1/ 6}{1/ 3} = \frac{1}{2} = P(B)$ 

About the Conditioned on C

To verify if $A$ and $B$ are independet conditioned on $C$, this identity has to hold:

$P(A\cap B | C) = P(A|C) P(B|C) $

$P(A\cap B | C) = \frac {P(A \cap B \cap C)}{P(C)} = P(\empty) = 0$

$P(A|C) = \frac {P(A \cap C)}{P(C)} = not zero$

$P(B|C) = \frac{P(B \cap C)}{P(C)}= not zero$

The indentity does not hold, so they are not idependent conditioned on $C$

***
**Question 13**:
For the Monty Hall problem, prove that by switching, your probablity of winning the car increases from $\frac{1}{3}$ to $\frac{2}{3}$. Hint: use Bayes Theorem!

**Solution**:

1. To find $ P(A|B) $, where $ A $ is the event that the car is behind the door you initially chose and $ B $ is the event that Monty opens a door revealing a goat:

    Using the law of total probability:
    
    $
    P(B) = P(B|A)P(A) + P(B|A')P(A') = \left( 1\cdot \frac{1}{3} \right) + \left( 1 \cdot \frac{2}{3} \right) = 1
    $

    We use Bayes' theorem:

    $
    P(A|B) = \frac{P(B|A)P(A)}{P(B)} = \frac{1 \cdot \frac{1}{3}}{1} = \frac{1}{3}
    $

2. To find $ P(A'|B) $, where $ A' $ is the event that the car is not behind the door you initially chose, we use Bayes' theorem:

    $
    P(A'|B) = \frac{P(B|A')P(A')}{P(B)} = \frac{1 \cdot \frac{2}{3}}{1} = \frac{2}{3}
    $

    So, the probability of winning by sticking with your initial choice is $ \frac{1}{3} $, and the probability of winning by switching is $ \frac{2}{3} $. It is better to switch.

***
**Question 14**:
For the Monty Hall problem, if Monty randomly choose a door to open, and it happens to be a goat. Prove that in this case, switching does not increase your probablity of wining the car! This is known as "The Random Monty Hall Problem".

**Solution**:

To find $ P(A|C) $, where $ A $ is the event that the car is behind the door you initially chose and $ C $ is the event that Monty opens a radom door revealing a goat:

$A$ and $C$ are independet events, because both of them choose randomly a door, so:

$$
P(C) = 2/3 = P(C|A)P(A) + P(C|A')P(A') = P(C)P(A) + P(C)P(A') = P(C)(P(A)+P(A'))
$$

$$
P(P(A)+P(A')) = 1
$$

$A'$ is the event of having a car in the door you didn't choose. But as we have to remaining doors and we can switch to only one, the probability is divided by two for each door.

So initially, the probability of $A$ and the probability to switch to any other door is $1/3$



***
**Question 15**:
Let $X$ have probability density function:
$$ f_X(x) = \begin{cases} \frac{1}{4} \quad &0 < x < 1 \\
\frac{3}{8} \quad &3 < x < 5 \\
0 \quad &\text{otherwise} \\
\end{cases}
$$
Find the cdf of $X$.

**Solution**:

To find the cumulative distribution function (CDF) of the random variable $X$ with the given probability density function (PDF), we need to integrate the PDF over its support. The CDF $F_X(x)$ is defined as:

$$
F_X(x) = \int_{-\infty}^{x} f_X(t) dt
$$

However, in this case, the PDF is defined as zero outside of the specified intervals $ (0 < x < 1 ; 3 < x < 5)$. So, we only need to consider these intervals in the integration.

For 0 < x < 1:
$$
F_X(x) = \int_{0}^{x} \frac{1}{4} dt + C_0 = \frac{1}{4} \cdot t \Big|_{0}^{x} + C_0 = \frac{1}{4}x + C_0 = \frac{1}{4}x
$$

For 3 < x < 5:
$$
F_X(x) = \int_{3}^{x} \frac{3}{8} dt + C_1 = \frac{3}{8} \cdot t \Big|_{3}^{x} + C_1 = \frac{3}{8}(x - 3) + C_1 = \frac{3}{8}(x - 3) + \frac{1}{4}
$$

For all other values of $x$, the CDF is zero.

So, the cumulative distribution function $F_X(x)$ for the given random variable $X$ is as follows:

$$
F_X(x) = \begin{cases} 
0 \quad &\text{for } x \leq 0 \\
\frac{1}{4}x \quad &\text{for } 0 < x < 1 \\
\frac{1}{4} \quad &\text{for } 1 \leq x < 3 \\
\frac{3}{8}(x - 3) + \frac{1}{4} \quad &\text{for } 3 \leq x < 5 \\
1 \quad &\text{for } x \geq 5 \\
\end{cases}
$$

This is the CDF of the random variable $X$ as defined by the given PDF.

***
**Question 16**:
Let $X$ have probability density function in previous question. Let $Y = 1/X$. Find the probability density function $f_Y(y)$ for $Y$.

(Hint: consider 3 cases: $\frac{1}{5} \leq y \leq \frac{1}{3}$, $\frac{1}{3} \leq y \leq 1$ and $y \geq 1$.)

**Solution**:

The random variable $X$ is described by a probability density function (pdf) $f_X(x)$ that satisfies:

$$
\int_{-\infty}^{\infty} f_X(x) \, dx = 1
$$

If we transform $X$ into a new variable $Y = g(X)$, we're interested in finding the new pdf $f_Y(y)$ such that:

$$
\int_{-\infty}^{\infty} f_Y(y) \, dy = 1
$$

We have to ensure that probabilities are conserved under the transformation $g$. This means that for any given set $A$,

$$
P(Y \in A) = P(X \in g^{-1}(A))
$$

To derive this, consider the cumulative distribution function (CDF) $F_Y(y)$ of $Y$, defined as:

$$
F_Y(y) = P(Y \leq y)
$$

By the chain rule of calculus,

$$
F_Y(y) = P(Y \leq y) = P(g(X) \leq y) = P(X \leq g^{-1}(y)) = F_X(g^{-1}(y))
$$

Differentiating both sides with respect to $y$, we get:

$$
f_Y(y) = f_X(g^{-1}(y)) \left| \frac{dy}{d g^{-1}(y)} \right|
$$

The change of variables formula for finding $f_Y(y)$ is:

$$
f_Y(y) = f_X(x) \left| \frac{dY}{dX} \right|
$$

The absolute value in the change of variables formula, $f_Y(y) = f_X(x) \left| \frac{dY}{dX} \right|$, is necessary to ensure that the probability density function $f_Y(y)$ is a valid PDF. Specifically, it guarantees that the function is non-negative over its entire domain.

## Transformation of Random Variable

We start by looking at the equation $Y = \frac{1}{X}$. Solving for $X$, we get:

$$
X = \frac{1}{Y} \Rightarrow x = \frac{1}{y}
$$

The derivative of $x$ with respect to $y$ is:

$$
\frac{dy}{dx} = -\frac{1}{y^2}
$$

## Case Analysis

Now, let's analyze the PDF of $Y$ in the context of the three cases: $\frac{1}{5} \leq y \leq \frac{1}{3}$, $\frac{1}{3} \leq y \leq 1$ and $y \geq 1$.

$$
f_X(x) = 
\begin{cases}
    \frac{1}{4} \quad &0 < x < 1 \\
    \frac{3}{8} \quad &3 < x < 5 \\
    0 \quad &\text{otherwise} \\
\end{cases}
$$


### Case 1: $ \frac{1}{5} \leq y \leq \frac{1}{3} $

- Corresponding $x$-interval: $ 3 \leq x \leq 5 $
- $f_X(x) = \frac{3}{8}$
- $f_Y(y) = \frac{3}{8y^2}$

### Case 2: $ \frac{1}{3} \leq y \leq 1 $

- Corresponding $x$-interval: $ 1 \leq x \leq 3 $
- $f_X(x) = 0$
- $f_Y(y) = 0$

### Case 3: $ y \geq 1 $

- Corresponding $x$-interval: $ 0 < x \leq 1 $
- $f_X(x) = \frac{1}{4}$
- $f_Y(y) = \frac{1}{4y^2}$

By analyzing these cases, we get a complete view of the PDF $f_Y(y)$ under the transformation $Y = \frac{1}{X}$.

$$
f_Y(y) = 
f_Y(y) = 
\begin{cases} 
\frac{3}{8y^2}, & \frac{1}{5} \leq y < \frac{1}{3} \\
\frac{1}{4y^2}, & y \geq 1 \\
0, & \text{otherwise} 
\end{cases}
$$





***
**Question 17**:
Let $X$ be a continous random variable with pdf $f_X(x)$ and cdf $F_X(x)$. Let $A$ be a subset of the real line. Let $I_A(x)$ be the indicator function for A:
$$ I_A(x) = \begin{cases} 1 \quad x \in A \\
0 \quad x \not\in A 
\end{cases}$$
Let $Y = I_A(x)$. Find an expression for the cdf of Y. 

(Hint: first find the probablity mass function for $Y$.)

**Solution**:

### Probability Mass Function of $Y$

$Y$ is a discrete random variable that takes on two values: 1 if $x \in A$ and 0 if $x \not\in A$. Therefore, its PMF $P_Y(y)$ can be defined as:

$$
P_Y(y) =
\begin{cases}
P(X \in A) & \text{if } y = 1 \\
P(X \not\in A) & \text{if } y = 0 \\
0 & \text{otherwise}
\end{cases}
$$

Here, $P(X \in A)$ is simply $\int_{A} f_X(x) \, dx$ and $P(X \not\in A) = 1 - P(X \in A)$.

### Cumulative Distribution Function of $Y$

The CDF $F_Y(y)$ is defined as $F_Y(y) = P(Y \leq y)$. Based on the PMF, we can find $F_Y(y)$ as follows:

$$
F_Y(y) =
\begin{cases}
0 & \text{if } y < 0 \\
P(X \not\in A) & \text{if } 0 \leq y < 1 \\
1 & \text{if } y \geq 1
\end{cases}
$$

Here, the value at $y = 0$ is $P(X \not\in A)$ and the value at $y = 1$ is $P(X \not\in A) + P(X \in A) = 1$.


***
**Question 18**: Let $X$ and $Y$ have the joind pdf:
$$ f_{X, Y}(x, y) = \begin{cases} c( x + y^2) \quad &0 \leq x \leq 1 \text{ and } 0 \leq y \leq 1 \\
0 \quad &\text{otherwise} \end{cases} $$
Find the value of c.

**Solution**:

To find the value of $c$, we need to ensure that the joint PDF integrates to 1 over its entire domain.

First, let's integrate $f_{X, Y}(x, y)$ with respect to both $x$ and $y$ over the specified domain:

$$
\int_0^1 \int_0^1 c(x + y^2) \, dx \, dy
$$

We first integrate with respect to $x$:

$$
c \int_0^1 \left[ \frac{x^2}{2} + xy^2 \right]_0^1 \, dy = c \int_0^1 \left( \frac{1}{2} + y^2 \right) \, dy
$$

Now, we integrate this result with respect to $y$:

$$
c \left[ \frac{y}{2} + \frac{y^3}{3} \right]_0^1 = c \left( \frac{1}{2} + \frac{1}{3} \right) = c \left( \frac{5}{6} \right)
$$

Since the total probability should equal 1:

$$
c \left( \frac{5}{6} \right) = 1 \Rightarrow c = \frac{6}{5}
$$


***
**Question 19**: Let  𝑋  and  𝑌  have the same joind pdf as previous problem. Find the marginal pdf of Y.

**Solution**:

To find the marginal probability density function (PDF) of $Y$ from the given joint PDF $f_{X, Y}(x, y)$ with $c = \frac{6}{5}$, we'll integrate the joint PDF with respect to $x$, effectively marginalizing out $X$. The marginal PDF of $Y$, denoted as $f_Y(y)$, can be found using the following formula:

$$
f_Y(y) = \int_{-\infty}^{\infty} f_{X, Y}(x, y) \, dx
$$

Given the joint PDF:

$$
f_{X, Y}(x, y) = 
\begin{cases} 
\frac{6}{5}(x + y^2) & 0 \leq x \leq 1, \, 0 \leq y \leq 1 \\
0 & \text{otherwise}
\end{cases}
$$

Let's calculate the marginal PDF $f_Y(y)$:

For $0 \leq y \leq 1$, we have:

$$
f_Y(y) = \int_{0}^{1} \frac{6}{5}(x + y^2) \, dx = \frac{6}{5} \left[\frac{x^2}{2} + y^2x\right]_0^1 = \frac{6}{5} \left(\frac{1}{2} + y^2\right) - 0 = \frac{3}{5} + \frac{6y^2}{5}
$$

So, the marginal PDF of $Y$ is:

$$
f_Y(y) = 
\begin{cases} 
\frac{3}{5} + \frac{6y^2}{5} & 0 \leq y \leq 1 \\
0 & \text{otherwise}
\end{cases}
$$

***
**Question 20**: Let  𝑋  and  𝑌  have the same joind pdf as previous problem. Find $P(X < \frac{1}{2} | Y = \frac{1}{2})$

**Solution**:

In a continuous joint PDF, the conditional probability $P(X < \frac{1}{2} | Y = \frac{1}{2})$ refers to the probability that $X$ is less than $\frac{1}{2}$ given that $Y$ is exactly $\frac{1}{2}$. In other words, it's the probability of a specific event in a continuous distribution.

In this case, the joint PDF is defined as:

$$
f_{X, Y}(x, y) = 
\begin{cases} 
\frac{6}{5}(x + y^2) & 0 \leq x \leq 1, \, 0 \leq y \leq 1 \\
0 & \text{otherwise}
\end{cases}
$$

To find $P(X < \frac{1}{2} | Y = \frac{1}{2})$, we need to calculate the conditional probability at $Y = \frac{1}{2}$:

$$
P(X < \frac{1}{2} | Y = \frac{1}{2}) = \int_{-\infty}^{\frac{1}{2}} \frac{f_{X, Y}(x, \frac{1}{2})}{f_Y(\frac{1}{2})} dx = \int_{0}^{\frac{1}{2}} \frac{f_{X, Y}(x, \frac{1}{2})}{f_Y(\frac{1}{2})} dx
$$

Where $f_{X, Y}(x, \frac{1}{2})$ is the joint PDF evaluated at $Y = \frac{1}{2}$, and $f_Y(\frac{1}{2})$ is the marginal PDF of $Y$ at $Y = \frac{1}{2}$.

Let's calculate this:

$$
f_{X, Y}(x, \frac{1}{2}) = \frac{6}{5} \left(x + \left(\frac{1}{2}\right)^2\right) = \frac{6}{5} \left(x + \frac{1}{4}\right)
$$

Now, we need to find $f_Y(\frac{1}{2})$, which is the marginal PDF of $Y$ at $Y = \frac{1}{2}$, from the previous example we have:

$$
f_Y(y) = 
\begin{cases} 
\frac{3}{5} + \frac{6y^2}{5} & 0 \leq y \leq 1 \\
0 & \text{otherwise}
\end{cases}
$$

Replacing:

$$
f_Y(\frac{1}{2}) = \frac{3}{5} + \frac{6 (1/2)^2}{5} = \frac{9}{10}
$$

The conditional probability:

$$
P(X < \frac{1}{2} | Y = \frac{1}{2}) = \int_{0}^{\frac{1}{2}} \frac{3}{4} \left(x + \frac{1}{4}\right) dx = \frac{3}{4} \left[\frac{1}{2}x^2 + \frac{1}{4}x\right]_{0}^{\frac{1}{2}} = \frac{3}{16}
$$


You're done with HW 1!  Be sure to...

* **Save and Checkpoint** from the File menu,
* **Close and Halt** from the File menu,
* **Rename your ipynb file**, replacing LASTNAME with your last name,
* **Upload** your file to the course website.